/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpgoneclick;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;


/**
 *
 * @author mateu
 */
public class Cadrastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadrastro
     */
    public Cadrastro() {
        initComponents();
        btngrup.add(Fem);
        btngrup.add(Masc);
        
    }
    ButtonGroup btngrup = new ButtonGroup();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Senha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        ConfirmeSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        Nick = new javax.swing.JTextField();
        Envia = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        MensagemSenha = new javax.swing.JLabel();
        Masc = new javax.swing.JRadioButton();
        Fem = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgoneclick/Imagens/AtiradorDiminuido.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel3.setText("Senha");

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel4.setText("Confirme");

        ConfirmeSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmeSenhaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel5.setText("Sexo");

        Envia.setText("Continuar");
        Envia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel6.setText("Nick: ");

        MensagemSenha.setForeground(new java.awt.Color(255, 0, 0));

        Masc.setText("Masculino");
        Masc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MascActionPerformed(evt);
            }
        });

        Fem.setText("Feminino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imagem)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Masc)
                                        .addGap(18, 18, 18)
                                        .addComponent(Fem))
                                    .addComponent(ConfirmeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nick, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MensagemSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(Envia)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConfirmeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MensagemSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Masc)
                            .addComponent(Fem))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Nick, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Envia)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Imagem)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed

    }//GEN-LAST:event_SenhaActionPerformed

    private void ConfirmeSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmeSenhaActionPerformed

    }//GEN-LAST:event_ConfirmeSenhaActionPerformed

    private void EnviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviaActionPerformed
        MensagemSenha.setText("");
        String linha = null;
            boolean vero = false;
            try {
                FileReader arqt = new FileReader("C:\\Banco\\Nicks.txt");
                BufferedReader lerArq = new BufferedReader(arqt);
                linha = lerArq.readLine();
                while (linha != null) {
                    if (linha.equals(Nick.getText()))
                        vero = true;
                    linha = lerArq.readLine();

                }
            } catch (IOException erro) { }
            if (vero == false) {
        
        
            if (ID.getText().isEmpty())
                MensagemSenha.setText("Há algo errado! Tente novamente");
            else if (Senha.getText().isEmpty() && ConfirmeSenha.getText().isEmpty())
                MensagemSenha.setText("Há algo errado! Tente novamente");            
            else if (!(Senha.getText().equals(ConfirmeSenha.getText())))
                MensagemSenha.setText("Há algo errado! Tente novamente");
            else if (!(Masc.isSelected()) && !(Fem.isSelected()))
                MensagemSenha.setText("Há algo errado! Tente novamente");
            else if (Nick.getText().isEmpty())
                MensagemSenha.setText("Há algo errado! Tente novamente");
            else {
                File arq = new File("C:\\Banco\\"+ID.getText()+".txt");
                File nike = new File ("C:\\Banco\\Nicks.txt");
                if (!(arq.exists())){
                JOptionPane.showMessageDialog(null, "Confirmação", "Conta criada com sucesso", JOptionPane.INFORMATION_MESSAGE);

                try {
                    FileWriter ni = new FileWriter (nike,true);
                    ni.write(Nick.getText()+"\r\n");
                    ni.flush();
                    ni.close();
                } catch (Exception erro) {
                    JOptionPane.showMessageDialog(null, "Erro", "Erro ao gravar a iformacao",JOptionPane.INFORMATION_MESSAGE);
                }
                
                
                
                try {
                    arq.createNewFile();
                    FileWriter fw = new FileWriter (arq);
                    fw.write(ID.getText()+"\r\n");
                    fw.write(Senha.getText()+"\r\n");
                    if (Masc.isSelected()) 
                        fw.write("Masculino"+"\r\n");
                    else if (Fem.isSelected())
                        fw.write("Feminino\r\n");
                    fw.write(Nick.getText()+"\r\n");
                    fw.write("iniciante"+"\r\n");
                   fw.flush();
                 fw.close();
                 dispose();
                 Login loginnr = new Login();
                 loginnr.setVisible(true);
                 loginnr.setLocationRelativeTo(null);
                 
                } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Arquivo não salvo.Erro: "+erro.getMessage());
                
                }
            }
                else 
                    JOptionPane.showMessageDialog(null, "Informação", "ID já utilizado", JOptionPane.INFORMATION_MESSAGE);
            }
            }
            else
                JOptionPane.showMessageDialog(null, "Erro", "Nick já existente", JOptionPane.INFORMATION_MESSAGE);
            ID.setText("");
            Senha.setText("");
            ConfirmeSenha.setText("");
            Nick.setText("");
    }//GEN-LAST:event_EnviaActionPerformed

    private void MascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MascActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadrastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadrastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadrastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadrastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadrastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmeSenha;
    private javax.swing.JButton Envia;
    private javax.swing.JRadioButton Fem;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel Imagem;
    private javax.swing.JRadioButton Masc;
    private javax.swing.JLabel MensagemSenha;
    private javax.swing.JTextField Nick;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
