/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpgoneclick;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mateu
 */
public class HistoryBeginning extends javax.swing.JFrame {

    /**
     * Creates new form HistoryBeginning
     */
    private static Musica1 m;
    public HistoryBeginning(Musica1 mus) {
        m = mus;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    public int cont;
    public void TextBeginning () throws FileNotFoundException {
        new Thread() {
            @Override
            public void run() {
                cont = 0;
                String linha;
                FileReader arqt;
                try {
                    arqt = new FileReader("C:\\RPGOneClick\\src\\rpgoneclick\\Textos\\Historia Principal.txt");
                    BufferedReader lerArq = new BufferedReader(arqt);
                    
                    do {
                        Nivel9.setText(Nivel8.getText());
                        Nivel8.setText(" ");
                        Thread.sleep(500);
                        Nivel8.setText(Nivel7.getText());
                        Nivel7.setText(" ");
                        Thread.sleep(500);
                        Nivel7.setText(Nivel6.getText());
                        Nivel6.setText(" ");
                        Thread.sleep(500);
                        Nivel6.setText(Nivel5.getText());
                        Nivel5.setText(" ");
                        Thread.sleep(500);
                        Nivel5.setText(Nivel4.getText());
                        Nivel4.setText(" ");
                        Thread.sleep(500);
                        Nivel4.setText(Nivel3.getText());
                        Nivel3.setText(" ");
                        Thread.sleep(500);
                        Nivel3.setText(Nivel2.getText());
                        Nivel2.setText(" ");
                        Thread.sleep(500);
                        Nivel2.setText(Nivel1.getText());
                        Nivel1.setText(" ");
                        Thread.sleep(500);
                        linha = lerArq.readLine();
                        Nivel1.setText(linha);
                        Thread.sleep(500);
                    } while (linha != null);
      
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(HistoryBeginning.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException | InterruptedException ex) {
                    Logger.getLogger(HistoryBeginning.class.getName()).log(Level.SEVERE, null, ex);
                }
                m.paraMusica();
                Mapa M1 = new Mapa();
                M1.setVisible(true);
                dispose();
            }
        }.start();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Skip = new javax.swing.JButton();
        Nivel9 = new javax.swing.JLabel();
        Nivel8 = new javax.swing.JLabel();
        Nivel7 = new javax.swing.JLabel();
        Nivel6 = new javax.swing.JLabel();
        Nivel5 = new javax.swing.JLabel();
        Nivel4 = new javax.swing.JLabel();
        Nivel3 = new javax.swing.JLabel();
        Nivel2 = new javax.swing.JLabel();
        Nivel1 = new javax.swing.JLabel();
        TelaFundo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Skip.setText("Skip");
        btn_Skip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SkipActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Skip, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        Nivel9.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        Nivel9.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Nivel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 960, 30));

        Nivel8.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        Nivel8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Nivel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 960, 30));

        Nivel7.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        Nivel7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Nivel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 960, 30));

        Nivel6.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        Nivel6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Nivel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 960, 30));

        Nivel5.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        Nivel5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Nivel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 960, 30));

        Nivel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        Nivel4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Nivel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 960, 30));

        Nivel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        Nivel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Nivel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 960, 30));

        Nivel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        Nivel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Nivel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 960, 30));

        Nivel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        Nivel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Nivel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 960, 30));

        TelaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgoneclick/Imagens/TexturaPreta.jpg"))); // NOI18N
        getContentPane().add(TelaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            TextBeginning();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HistoryBeginning.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btn_SkipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SkipActionPerformed
        System.out.println("Sai batata");
        dispose();
        File fi = new File ("C:\\RPGOneClick\\src\\rpgoneclick\\Sounds\\Beethoven   Silence.mp3");
        Musica1 M = new Musica1(fi);
        Mapa mapa = new Mapa();
        mapa.setVisible(true);
        //h.setVisible(true);
        m.paraMusica();
    }//GEN-LAST:event_btn_SkipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryBeginning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryBeginning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryBeginning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryBeginning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryBeginning(m).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nivel1;
    private javax.swing.JLabel Nivel2;
    private javax.swing.JLabel Nivel3;
    private javax.swing.JLabel Nivel4;
    private javax.swing.JLabel Nivel5;
    private javax.swing.JLabel Nivel6;
    private javax.swing.JLabel Nivel7;
    private javax.swing.JLabel Nivel8;
    private javax.swing.JLabel Nivel9;
    private javax.swing.JLabel TelaFundo;
    private javax.swing.JButton btn_Skip;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
