/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpgoneclick;

/**
 *
 * @author mateu
 */
public class Livro extends javax.swing.JFrame {

    /**
     * Creates new form Livro
     */
    public Livro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rain = new javax.swing.JLabel();
        FireGround = new javax.swing.JLabel();
        Curar = new javax.swing.JLabel();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Rain.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Rain.setText("Storm - É uma técnica de evocar um raio em seu cajado");
        getContentPane().add(Rain, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        FireGround.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        FireGround.setText("Fire Blast - É uma técnica que cria uma explosao de chamas");
        getContentPane().add(FireGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        Curar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        Curar.setText("Healing - Cura");
        getContentPane().add(Curar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgoneclick/Imagens/Bola eletromagnetizada.png"))); // NOI18N
        getContentPane().add(imagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -180, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Livro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Curar;
    private javax.swing.JLabel FireGround;
    private javax.swing.JLabel Rain;
    private javax.swing.JLabel imagemFundo;
    // End of variables declaration//GEN-END:variables
}
